### ISSUE TITLE
Memoize not working properly with arrays

### ISSUE THREAD

**Issue by ohoho7** [alexreardon/memoize-one#102]
Doc has statement:
Tested with all built in JavaScript types.
But it is not working properly with arrays, example:
```
function sum(parameter: number[]) {
    return parameter.reduce((acc, elem) => acc + elem, 0);
}
const memoizedSum = memoize(sum);
const myArr = [7];

console.log(memoizedSum(myArr)); // 7
myArr.push(7);
console.log(myArr); // [7,7]
console.log(memoizedSum(myArr)); //7
```

**Comment by alexreardon** [comment]
it is currently doing a `===` check. From the docs:

> The default equality function is a shallow equal check of all arguments (each argument is compared with ===)

`.push()` is modifying an array and not creating a new array. So the `===` check is not capturing this change.

I need to think about whether we should keep it as is or make a modification

**Comment by alexreardon** [comment]
Feel free to comment if this is still a problem for you
