### ISSUE TITLE
Doc: please update the performance numbers + the benchmark

### ISSUE THREAD

**Issue by Offirmo** [alexreardon/memoize-one#108]
Hi and thanks for this amazing lib!

The benchmarks section:
1. is outdated. The benchmark page says "4 years ago"
1. it can't be run anymore
1. I'd be interested in replacing moize with https://github.com/planttheidea/micro-memoize (which is internally used by moize)

Could it be updated?
Thanks!

**Comment by alexreardon** [comment]
I think it should be updated! A pr to get started would be awesome

**Comment by alexreardon** [comment]
I am doing this as a part of #124
