### ISSUE TITLE
3.1.0 breaks IE11

### ISSUE THREAD

**Issue by eugene1g** [alexreardon/memoize-one#20]
Hi,

I'm using https://github.com/atlassian/react-beautiful-dnd which depends on this project. With the release of 3.1, this library appears to break IE11 with an error `cannot redefine non-configurable property length` which I traced back to https://github.com/alexreardon/memoize-one/blob/master/src/index.js#L45 which was added in 3.1

If I forcefully revert to 3.0.1, IE11 works well again. Sorry I do not have a good test-case, so just heads up that there might be an issue with 3.1 which gets pulled into `react-beautiful-dnd` by default now.

**Comment by alexreardon** [comment]
Damn. Thanks.

@theKashey looks like the best path forward for now is to drop our .length (and .name?) modifications

**Comment by alexreardon** [comment]
I am not keen to try an sniff if we are operating in IE11 - especially as this module can be used in browser or in node. I think for now we should role back this change

**Comment by alexreardon** [comment]
Or wrap things in a try/catch... thoughts?

**Comment by theKashey** [comment]
Would you welcome some eval in your code? https://github.com/blakeembrey/arity

**Comment by alexreardon** [comment]
I have rolled back the .length and .name addition for now. 

I have deprecated 3.1.0 and published 3.1.1 which does not modify the function properties. This gives us some breathing room to think about this a bit more and test approaches

**Comment by alexreardon** [comment]
@eugene1g can you please try again and let me know how you go? Thanks for picking this up so quickly. Because it was so quick I was able to deprecate 3.1

**Comment by eugene1g** [comment]
@alexreardon That fix worked! Thank you for such a quick turnaround :)
