### ISSUE TITLE
Memoize All

### ISSUE THREAD

**Issue by PascalSenn** [alexreardon/memoize-one#23]
What about an optional argument to memoize all function calls? 

That could be very helpful for event handler creators. 

For example:

```jsx
          <Line
            key={line.id}
            onMouseClick={this.createOnMouseClickLine(line.id)}
          />
```

**Comment by alexreardon** [comment]
That functionality goes outside of the scope of this library. I would suggest you use a memoization library with an unbounded cache such as [lodash.memoize](https://www.npmjs.com/package/lodash.memoize)
