### ISSUE TITLE
"This expression is not callable" type error when trying to use this package from ESM module

### ISSUE THREAD

**Issue by kaiyoma** [alexreardon/memoize-one#265]
I've been using memoize-one from CJS for many years, but when I try to convert the calling code to ESM, I now get this error:

```
src/lib.ts:73:21 - error TS2349: This expression is not callable.
  Type 'typeof import(".../common/temp/node_modules/.pnpm/memoize-one@6.0.0/node_modules/memoize-one/dist/memoize-one")' has no call signatures.
```

I'm pretty sure my import is correct:

```
import memoizeOne from 'memoize-one';
```

I'm not getting this error with any other dependency, so it seems specific to memoize-one. My package still builds correctly, which means it's maybe just an error with the types. I'm using the latest version (6.0.0).

**Comment by kaiyoma** [comment]
Switching to Vite/Vitest (away from webpack/Jest) fixed this issue for me.

**Comment by samhh** [comment]
I'm seeing the same with typechecking with `"moduleResolution": "Node16"`. You can workaround it like so:

```ts
import _memoizeOne from 'memoize-one';

const memoizeOne = _memoizeOne as unknown as typeof _memoizeOne.default;
```
