### ISSUE TITLE
Not working for typescript

### ISSUE THREAD

**Issue by theKashey** [alexreardon/memoize-one#37]
Actually the problem is not with typescript - the problem is with rollup.

https://unpkg.com/memoize-one@4.0.2/dist/memoize-one.cjs.js contains
```js
module.exports = index;
```
which should be imported as `import * as memoizeOne`

while https://unpkg.com/memoize-one@4.0.2/dist/memoize-one.esm.js contains
```js
export default index;
```
which should be imported as `import memoizeOne`

Result - the code for nodejs (~jest) require one behaviour, while the code for webpack(uses esm bundle) requires another.

It is not a problem for js/flow, as long babel is doing some around magic default imports, but typescript is quite strict about it.

The cjs bundle should match esm bundle.

(and fixing this would introduce a breaking change)

**Comment by alexreardon** [comment]
@TrySound thoughts?

**Comment by alexreardon** [comment]
As you mentioned @theKashey we are using rollup to generate the bundles. It sounds like there is an issue with the `cjs` bundle. Is there an option we can change for the rollup build...?

**Comment by TrySound** [comment]
This is the old issue with typescript itself and default exports. My solution is getting rid from default exports in the next major release. They are quite useless.

I'm not alone.
https://github.com/jaredpalmer/formik/pull/973#issuecomment-428012717

**Comment by TrySound** [comment]
@theKashey cjs bundle is matched to esm bundle by the way, it's typescript fault.

**Comment by MrKWatkins** [comment]
I've added the following function as a workaround which I call at the start of my tests:

```
export function ensureMemoizeOneInitialized()
{
    if (typeof memoize === "undefined")
    {
        /* tslint:disable:no-var-requires */
        (memoize as any) = require("memoize-one");
    }
}
```

**Comment by alexreardon** [comment]
I would be keen to find a way forward in our generated code. Ideally it would work with TS out of the box. Any thoughts @TrySound?

**Comment by TrySound** [comment]
This is the best and not only for typescript
https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html

**Comment by TrySound** [comment]
Actually there is `esModuleInterop` flag which fixes this behaviour in typescript similar to "magical" (it's not) babel way.

**Comment by TrySound** [comment]
It should be default since v3 but "TS has such big ecosystem".

**Comment by alexreardon** [comment]
Could you make a PR? 🤘

**Comment by TrySound** [comment]
To typescript? I'm not. Users should enable it and fix all modules in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by TrySound** [comment]
Or do you mean named export?

**Comment by theKashey** [comment]
Please don't use `esModuleInterop` or `allowSyntheticDefaultImports`, it will require target consumer to set it, and this is something you shall not ask for.
PS: And also affects imports, not exports.

**Comment by TrySound** [comment]
@theKashey That's the point. It should be default. Ecosystem is broken now. It's just doesn't work for many packages.

**Comment by alexreardon** [comment]
> To typescript? I'm not. Users should enable it and fix all modules in DefinitelyTyped.
@TrySound I misunderstood you. I thought we could add a simple rollup plugin and be done with this issue

It sounds like you have some insight into this @theKashey, any thoughts on how to proceed?

**Comment by TrySound** [comment]
Well another option is named only exports.

**Comment by theKashey** [comment]
The best option I could provide, would be a :badjookeeee: option - rewrite memoize-one to TS, and provide .flow types in a separate, ie "revert" how it works today.
TS could generate "default" exports, understandable both by TS and JS.

**Comment by TrySound** [comment]
@theKashey What is the point of esModuleInterop if it doesn't work with any typings at all? What for they provided broken configuration?

**Comment by TrySound** [comment]
@theKashey It's not the best option. It's a hack for hacky ecosystem.

**Comment by TrySound** [comment]
Flow is not opinionated and that's why it's so beautiful.

**Comment by theKashey** [comment]
Technically - 
```js
Object.defineProperty(exports, "__esModule", {
  value: true
});

exports = memoizeOne;
exports.default = memoizeOne;
```

**Comment by alexreardon** [comment]
Can we add that to the cjs build?

**Comment by theKashey** [comment]
That could be a little problem.

**Comment by TrySound** [comment]
Babel moved from this hack two major versions ago.

**Comment by wmhilton** [comment]
I'm running into this problem as well. Not sure if it's TypeScript per-se or Jest.

But the crux of it is that the CJS module needs to include a named export called "default". Pretty much like @theKashey showed.

I think that would fix it.

**Comment by wmhilton** [comment]
Just tried. Can't be done. (Seriously `rollup`?) Default exports were such a fuckup. :(

I think the only way out is to release a new major version that breaks the way CJS currently works and forces it to use `require('memoize').default`. I'll make a PR.

**Comment by wmhilton** [comment]
@hlolli you can use https://npmjs.org/package/@stoplight/memoize-one (based on #40)

**Comment by hlolli** [comment]
Thanks for the replies. I tried the `esModuleInterop` (it works!) and it seemed to me, that I had to use it sooner or later, since `import * as ... ` is quite ugly. I'll make a bet still that this will not be the last of tickets relating this issue if this is needed :)

**Comment by damiangreen** [comment]
Is there a resolution for this in SSR apps?

**Comment by TrySound** [comment]
@damiangreen `esModuleInterop: true`

**Comment by damiangreen** [comment]
eek, turning that on gives me about 30  TS2349 errors across my application, not really a solution @TrySound without big refactorings

**Comment by TrySound** [comment]
Try allowSyntheticDefaultImports

**Comment by damiangreen** [comment]
I have  that enabled already :/

**Comment by TrySound** [comment]
Well, 30 import statements is not so much to tweak.

**Comment by damiangreen** [comment]
actually i started trying to refactor my app, but it turns out it would require touching more than 30 imports  but its about a years worth of dev and i dont really want to to a full regression test just to import a library , not on a friday night anyway.

**Comment by sbaechler** [comment]
Another workaround is to create a new **.js** file with a named export:

    export { default as memoizeOne } from 'memoize-one';

and import from there.

**Comment by TrySound** [comment]
@sbaechler Why is it different from `import memoizeOne from 'memoize-one';`?

**Comment by sbaechler** [comment]
I have no idea. It is not any different, but it is working. I guess Typescript or Jest are using a different import resolution since it is importing a .js file and not a .ts file.

**Comment by TrySound** [comment]
@sbaechler Do you use babel to transpile TS or ts-jest?

**Comment by sbaechler** [comment]
We are using Babel. The config is based on a fork of create-react-app 1. I noticed that this issue does not occur anymore on create-react-app 2 based projects.

**Comment by skidding** [comment]
Not sure if we're all experiencing the same issue, but here's how I solved mine.

Added this declaration for `memoize-one` in my project and removed `@types/memoize-one`

```ts
declare module 'memoize-one' {
  export type EqualityFn = (a: any, b: any, index: number) => boolean;

  declare function memoizeOne<T extends (...args: any[]) => any>(
    resultFn: T,
    isEqual?: EqualityFn
  ): T;

  export = memoizeOne;
}
```

The problem could be that the official types are for 4.1 and I'm using 5.0.

If anyone wants to publish this to DefinitelyTyped (or in the memoize-one codebase directly) be my guest.

**Comment by damiangreen** [comment]
@skidding this works a treat, thanks for posting

**Comment by alexreardon** [comment]
@TrySound should we add the definition of @skidding to the project?

**Comment by pablofmena** [comment]
Hi, first thanks for this neat utility and for caring about the TypeScripters 😃

If you plan to make the type definition file part of the project, here my two cents for version 5:

```ts
declare function memoizeOne<T extends (...args: any[]) => any>(
  resultFn: T,
  isEqual?: memoizeOne.EqualityFn<T>
): T;

declare namespace memoizeOne {
  type EqualityFn<T extends (...args: any[]) => any> = (
    newArgs: Parameters<T>,
    oldArgs: Parameters<T>
  ) => boolean;
}

export = memoizeOne;
```

- So instead of naming just `a` and `b` to the parameters, they are named `newArgs` and `oldArgs` to give a little bit more context.
- Using a generic type argument as well on `EqualityFn` to take advantage of the built-in `Parameters<T>` type and avoid the use of the permissive `any` type. This way you also leverage type inference while passing this parameter, so no need to type the arguments yourself.

**Comment by TrySound** [comment]
@alexreardon I guess the issue will never end until we migrate to `require('memoize-one').default` solution. This can be done with `output.exports: 'named'` option.

**Comment by TrySound** [comment]
And yeah, having builtin definitions will be good for ts users.

**Comment by alexreardon** [comment]
@TrySound if we add a TS definition would this allow TS users to have correct typing without needing to do anything else?

**Comment by TrySound** [comment]
Yes, I think so with TS definition and output.exports: 'named'

**Comment by thomasmikava** [comment]
If I change 
```ts
export = memoizeOne;
```
to
```ts
export default memoizeOne;
```
everything works fine. However, If I change import from 
```ts
import memoizeOne from "memoize-one";
```
to
```ts
import * as memoizeOne from "memoize-one";
```
the compilation of my React project fails.

Thus, I am forced to change index.d.ts file as I said (or downgrade memoize-one)

**Comment by TrySound** [comment]
@alexreardon Another solution is dropping default export.
```js
import { memoizeOne } from 'memoize-one';
```

**Comment by thomasmikava** [comment]
@TrySound In case of writing { memoizeOne }, I get the following message:
```
Module '"../../../../node_modules/@types/memoize-one"' has no exported member 'memoizeOne'
```

**Comment by TrySound** [comment]
@thomasmikava 
It's proposal for the project.
Do you have `esModuleInterop` or `allowSyntheticDefaultImports` enabled?

**Comment by thomasmikava** [comment]
@TrySound 
No, I don't

**Comment by TrySound** [comment]
They should be enabled to provide cjs/esm interop.

**Comment by tyleo** [comment]
This was broken for me. I eventually fixed it but I consider that work to be more of a chain of unfortunate hacks than I consider it a fix.

I'm in a monorepo using memoize-one across a few projects. We have an electron project and a website. memoize-one did not work out of the box on the electron project. Out of roughly 15 other modules I am using, memoize-one is the only module which does not work out of the box. To fix the electron project, I isolated memoize-one in its own project in our monorepo with the following code:
```
import * as memoizeOne_ from "memoize-one";

export = <T extends (...args: any[]) => any>(resultFn: T, isEqual?: memoizeOne_.EqualityFn): T => {
    return (memoizeOne_ as any)(resultFn, isEqual);
};
```

This was working fine for awhile but broke when we started to use memoize-one on our website. Luckily, since I isolated memoize-one to its own project I could add `"esModuleInterop": true` to it without impacting the other projects. After this I updated my code:
```
import * as memoizeOne_ from "memoize-one";

export = <T extends (...args: any[]) => any>(resultFn: T, isEqual?: memoizeOne_.EqualityFn): T => {
    return (memoizeOne_ as any).default(resultFn, isEqual);
};
```

I'm not personally thrilled about this solution but I'm glad that I could at least isolate the impact of `esModuleInterop` to a single project.

I think memoize-one is a great tool and it could be even greater if it worked out of the box for typescript projects in a standard way without requiring `esModuleInterop`.

**Comment by theKashey** [comment]
So! Working for TypeScript #72!!!

**Comment by theKashey** [comment]
Not working in Jest/node environment in the same way it was not working before. 
Cjs bundle is broken without esModuleInterop

**Comment by alexreardon** [comment]
PR welcome @theKashey 👍

**Comment by theKashey** [comment]
There are two ways, please pick any to "fix" the issue, without breaking changes for `cjs` and non `typescript` users (ie node):
- keep the current "default" export, and add memoizeOne as a __named export__ next to it. However - that would bring some confusion.
- keep everything as is. Define `.default` on memoizeOne itself, so `cjs` export would be both `cjs` and `esm` compatible. Hacky hack, but would work. (don't tell anybody I've proposed it)

**Comment by TrySound** [comment]
Or just enable esModuleInterop and ask ts maintainers to do the same :)

**Comment by haraldschilly** [comment]
I also stumbled over this typerscript code vs. jest testing problem. What I ended up doing is this:

```
import * as memoizeOneModule from "memoize-one";
const memoizeOne =
  typeof memoizeOneModule.default === "function"
    ? memoizeOneModule.default
    : memoizeOneModule;
```

I hope the typescript gods have mercy …

**Comment by alexreardon** [comment]
@theKashey i think having the named export is the least strange. Thoughts @TrySound ?

```js
export default function memoizeOne(){...}
export { memoizeOne };
```

**Comment by theKashey** [comment]
That's the only way to fix the situation without a breaking change.

**Comment by TrySound** [comment]
Having only named export is ok
```
export function memoizeOne(){...}
```
and less confusing for commonjs users
```
import { memoizeOne } from 'memoize-one';
const { memoizeOne } = require('memoize-one');
```
vs
```
import memoizeOne from 'memoize-one';
const memoizeOne = require('memoize-one').default;
```

**Comment by theKashey** [comment]
But that would be a breaking change. However, I definitely agree - that would be the best solution.

**Comment by oonsamyi** [comment]
@alexreardon @theKashey @TrySound 
Any activities?
Can we add named export and leave default export?
I can make pull-request.

**Comment by TrySound** [comment]
@oonsamyi Why not enable interop on your side?

**Comment by oonsamyi** [comment]
When I add `esModuleInterop` option to ts config several dozen typescript errors appear and part of unit tests fails. Typescript errors are not a problem for me. But the failure tests are a problem. I don't quite understand why tests fail with esModuleInterop option.

Now I turned off `esModuleInterop` option and added next hack to jest config:
```js
// project/fixDefaultImports.ts
jest.mock('memoize-one', () => ({
  default: jest.requireActual('memoize-one'),
}));
```
```js
// project/jest.config.js
module.exports = {
  setupFilesAfterEnv: ['<rootDir>/enzyme.config.js', '<rootDir>/fixDefaultImports.ts'],
  ...
}
```

But it is hack...

Summary, I would like to work with default typescript config.
Is this issue accurate only with typescript? What about jest + pure javascript?
Is it hard to add named export? I think it is easy, memoize-one will be worked out of the box with typescript default config and many people will be grateful :)

P.S. React resolves this problem next way:
https://github.com/facebook/react/blob/master/packages/react/index.js#L16
It is cool because no matter what is used in the environment of the project: CommonJS or ES6 modules, javascript or typescript, webpack or rollup. It works for all the ones.

**Comment by TrySound** [comment]
> Summary, I would like to work with default typescript config.

This is not an option with typescript. You loose safety without strictNullChecks.

> Is it hard to add named export?

This is inconsistent design. There should be either default or named export.

> React resolves this problem next way:

React does not distribute esm and does not export function as default/module.exports.

> But it is hack...

This is too, but this is how ts behaves by default.
```js
import * as memoizeOne from 'memoize-one';
```

I'd say babel as compiler will solve all your issues.

**Comment by theKashey** [comment]
> Why not enable interop on your side?

then [classnames would be broken](https://github.com/JedWatson/classnames/issues/205) :)

**Comment by alexreardon** [comment]
I'm happy to add a named export if it is easier for people

**Comment by oonsamyi** [comment]
@TrySound Okay, thanks for the feedback.
I will try to use `esModuleInterop` option.

**Comment by oonsamyi** [comment]
@alexreardon Can I make a pull request?

**Comment by mits87** [comment]
Any news?

**Comment by filipef101** [comment]
Let's go

**Comment by theKashey** [comment]
Wasn't it solved in a new version?

**Comment by mits87** [comment]
It looks like still there is a problem. 
I have installed: `"memoize-one": "^5.1.1"`

When I'm trying to use it like that:
```
import memoizeOne from 'memoize-one';
```

I've got an error: 

```Uncaught Exception
{
  "errorType":"TypeError",
  "errorMessage":"memoize_one_1.default is not a function",
  "stack":[
    "TypeError: memoize_one_1.default is not a function", "......"]
}```

**Comment by TrySound** [comment]
@mits87 Try to enable esModuleInterop in TS config

**Comment by mits87** [comment]
Actually I can't use the `esModuleInterop` option because I have a lot of libraries like:

```import * as SQS from 'aws-sdk/clients/sqs';```

and after enabled `esModuleInterop` flag I've got errors like:

```Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.```

**Comment by TrySound** [comment]
Let's kill default import.
https://github.com/alexreardon/memoize-one/pull/86

**Comment by tamazlykar** [comment]
Any news?

I have a strange problem. I was using memoize-one without esModuleInterop and it works great with import like this:
`import * as memoizeOne from 'memoize-one'`
but when i set  esModuleInterop to true and change import to `import memoizeOne from 'memoize-one'` app still works but jest start to fails with ` TypeError: memoize_one_1.default is not a function`.
If I set a breakpoint around the place where memoize-one is used I see that memoize_one_1 looks like this:
```
memoize_one_1 : {
  default: {
    {
      default: actual_function 
    }
  }
}
```
App compiles with webpack and ts-loader, jest with ts-jest, typescript version is 3.7.5.
If this problem not relates to this library, sorry. 
Any ideas why this happens will be appreciated.

**Comment by TrySound** [comment]
@tamazlykar I faced this problem with webpack when some commonjs module imported esm version of library. Make sure you do not transpile modules by babel-loader.

**Comment by alexreardon** [comment]
i'm totally open to adding a `minor` release which allows people to use `memoize-one` as a named import

```ts
export const memoizeOne = memoizeOne;
export const memoize = memoizeOne;
```

**Comment by alexreardon** [comment]
Just to make peoples lives easier ^

**Comment by theKashey** [comment]
👍 `import { memoizeOne } from 'memoize-one';` - it will be better _autoimportable_.

Plus every time you `import memoizeOne from 'memoize-one'` [eslint will complain](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-named-as-default.md) about the named export and propose a change (actually that could break builds, but 😅 it is a good to have feature)

**Comment by cwood-panopto** [comment]
@alexreardon With the revert in v5.2.1 is this an issue again? I am still having the error in jest with ts: `TypeError: memoize_one_1.default is not a function`
