### ISSUE TITLE
Feature: ability to reset/clear cache of memoized function after using it

### ISSUE THREAD

**Issue by LyWf** [alexreardon/memoize-one#43]
Motivation:
memoize-one stores inside closure the last this, result and arguments. This may lead to the fact that references to large objects will be cached, and large objects won't be collected by the garbage collector.

Suggestion:
For instance, to add the static "reset" method to the returned function, which will reset lastThis, lastArgs, lastResult, calledOnce to the initial values.

**Comment by alexreardon** [comment]
You could achieve this by doing:

```js
memoized.apply({}, []);
```

**Comment by alexreardon** [comment]
I have not done this yet as a feature due to typing. the memoized function returns the same type as the function passed in. I cannot seem to express this type with an extension: a .reset property
