### ISSUE TITLE
New Equality function type signature breaks with a lot of equality functions

### ISSUE THREAD

**Issue by ehtb** [alexreardon/memoize-one#47]
Thanks for the great library! Just a heads up and something I think worth considering; adding the index to the equality callback causes a lot of commonly used equality functions to break.

For instance the most popular one, `shallowEqual` has as a third parameter a custom comparison function: `shallowequal(value, other, [customizer], [thisArg])`. Same is true for the lodash deep comparison function.

Of course it is not a huge problem to change this in our code, but it breaks a lot of existing code like this: `memoizeOne(params, shallowEqual)`

**Comment by alexreardon** [comment]
Oh snap. Perhaps we should role this back. Thoughts?

**Comment by alexreardon** [comment]
I was unsure about this one but I had no data to back up my unease

**Comment by alexreardon** [comment]
Based on your feedback I think I will role it back. I’ll have more of a
think about how to move forward

**Comment by ehtb** [comment]
Thanks for the fast reply, makes sense yes. 

Just my 2c, but from my perspective the current api does exactly what I need, so i would be conservative in extending it with new features.

**Comment by nihgwu** [comment]
From my perspective, a library should not be aware of the implementation of other libraries

The HOC idea is awesome, but it complicates the usability IMO, I agree we should roll back #42 as it breaks current usage suggested by the README
