### ISSUE TITLE
stronger flow typing?

### ISSUE THREAD

**Issue by chrisnojima** [alexreardon/memoize-one#53]
Firstly, thanks for the great library!

Just to start a discussion: locally i've been using this typing for this lib
```
declare export function memoize<A, B, C, D, R>(
  func: (a: A, b: B, c: C, d: D) => R,
  equalityCheck?: (newArgs: [A, B, C, D], lastArgs: [A, B, C, D]) => boolean
): (a: A, b: B, c: C, d: D) => R
```

this lets the equality check be more typed than `mixed`
A downside is if you export a memoized function you need to declare all your types
```
export default memoize<number, string, void, void, _>((num, str) => num + str)
```
(maybe this could be better if https://github.com/facebook/flow/issues/6875 was fixed)

has anyone else attempted a strong flow type?

**Comment by alexreardon** [comment]
We did not pursue this path even for the TS implementation. I think it requires to much heavy lifting for consumers while not delivering a heap of value. If these types could be inferred, that would be fantastic
