### ISSUE TITLE
Create debug helper

### ISSUE THREAD

**Issue by alexreardon** [alexreardon/memoize-one#54]
It would be good to know some information about cache breaking for debugging purposes. The big idea is that it could expose a lot of debug information on the `console`

I am not sure what the api would be, but here is some initial thoughts:

```js
import memoizeOne, { trace } from 'memoizeOne';

const times = (arg1: number, arg2: number): number => arg1 * arg2;
const memoized = memoizeOne(times);

trace(times(1, 2));
// first time call
// new arguments: [1, 2]
// returning new result: 2

trace(times(1, 2));
// new arguments [1, 2] match previous arguments
// returning previous result: 2

trace(times(1, 3));
// cache bust!
// new arguments [1, 3] do not match previous arguments [1, 2]
// argument change: [1, *2*]
// calculating new result and returning: 3
```

**Comment by alexreardon** [comment]
I am not sure if it should be an extra export, or perhaps controlled with a flag:

`window.__memoizeOne-tracing-enabled = true`

**Comment by alexreardon** [comment]
There could also be levels to the tracing

0 = no tracing
1 = log cache busts
2 = everything

`trace(times(1, 2), { level: 1 })`

**Comment by OliverJAsh** [comment]
It would also be useful to expose a `recomputations` function as a property on the memoized function, which is what reselect's `createSelector` does.
