### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by masoud-msk** [alexreardon/memoize-one#55]
The doc says:
> The default equality function also does not check anything if the length of the arguments changes.

which is not correct according to the current source code.

**Comment by alexreardon** [comment]
Let me take a look

**Comment by newyork-anthonyng** [comment]
The doc looks correct. The [`simpleIsEqual` function](https://github.com/alexreardon/memoize-one/blob/master/src/index.js#L11) checks if the arguments' length has changed. If the length has changed, `simpleIsEqual` returns `false` right away.

```js
newArgs.length === lastArgs.length &&
newArgs.every(
    (newArg: mixed, index: number): boolean =>
      shallowEqual(newArg, lastArgs[index]),
);
```

**Comment by masoud-msk** [comment]
'Check anything' was a little ambiguous for me. I thought it doesn't check argument length. 🤦‍♂️ 
After reading next sentence:
> You are welcome to decide if you want to return false if the length of the arguments is not equal.

I  thought you didn't do that now and the following snippet is a way to override the current behavior.
Sorry for my mistake.
