### ISSUE TITLE
Memoized function not re-executing when input object has changed since last execution

### ISSUE THREAD

**Issue by bjs250** [alexreardon/memoize-one#66]
Hey, don't know if this is the proper way to bring this up, but I was using this library to memoize data filtering functions before render in React, and for most purposes, this library has worked great. 

I had 3 inputs to the memoized function: an object, an array, and a string. When the array and string would change, the memoized function would work as expected (that is, it would re-execute). However, when an attribute nested several levels deep in the object would change, the memoized function would return the cached result rather than re-execute (and from what I understand, this would imply that the under-the-hood implementation may have an issue doing deep object comparison on the inputs, which is already a pain in the ass in Javascript)

**For anyone experiencing a similar issue, the workaround I used was to JSON.stringify the input object and use that as an additional memoized function argument**. Since the string representation changes when the object changes, the library understands to re-execute the memoized function

**Comment by natineprince** [comment]
I think it is caused by lastArgs assignment, it is just a simple assign from arguments, therefore, if you use a share object for argument, the lastArgs cache will be changed outer the closure. To avoid this, maybe we can make a deep clone object for call or just as @bjs250 said, use stringify.

**Comment by alexreardon** [comment]
By default, we do a simple equality check on each argument `===`. For objects, this checks that the reference to the object is the same, not the underlying values. This is a shallow equality check. If you need to do deep equality checking then please use the [custom equality function](https://github.com/alexreardon/memoize-one#custom-equality-function)
