### ISSUE TITLE
Move to typescript

### ISSUE THREAD

**Issue by alexreardon** [alexreardon/memoize-one#70]
Here is what I am thinking so far:

```js

export type EqualityFn = (newArgs: unknown[], lastArgs: unknown[]) => boolean;

function areInputsEqual(
  newInputs: unknown[],
  lastInputs: unknown[],
): boolean {
  // no checks needed if the inputs length has changed
  if (newInputs.length !== lastInputs.length) {
    return false;
  }
  // Using for loop for speed. It generally performs better than array.every
  // https://github.com/alexreardon/memoize-one/pull/59

  for (let i = 0; i < newInputs.length; i++) {
    // using shallow equality check
    if (newInputs[i] !== lastInputs[i]) {
      return false;
    }
  }
  return true;
}


export default function memoizeOne<ResultFn extends (this: unknown, ...newArgs: unknown[]) => ReturnType<ResultFn>>(
  this: unknown,
  resultFn: ResultFn,
  isEqual: EqualityFn = areInputsEqual,
): ResultFn {
  let lastThis: unknown;
  let lastArgs: unknown[] = [];
  let lastResult: ReturnType<ResultFn>;
  let calledOnce: boolean = false;

  // breaking cache when context (this) or arguments change
  function memoized(this: unknown, ...newArgs: unknown[]): ReturnType<ResultFn> {
    if (calledOnce && lastThis === this && isEqual(newArgs, lastArgs)) {
      return lastResult;
    }

    // Throwing during an assignment aborts the assignment: https://codepen.io/alexreardon/pen/RYKoaz
    // Doing the lastResult assignment first so that if it throws
    // nothing will be overwritten
    lastResult = resultFn.apply(this, newArgs);
    calledOnce = true;
    lastThis = this;
    lastArgs = newArgs;
    return lastResult;
  }

  return (memoized as ResultFn);
}

```

[playground](https://www.typescriptlang.org/play/#code/FAUwHgDg9gTgLgAjgTwiBBRAjgVwIYA2AligGIB2CAvAgBTkgDuAgjAOYDOAXAjuQNbkojcgG0AugBoEBPBzitOPPoOFjxASmoA+BACMoUAiDzkA3MGAAzPgGM4RKJTwwQASXIQccDtnwFaYAQEBkYPLx9lASERCUkgmTk4cO9uXmi1OOANHgMjE0oAbwSAehKQqARbAAsQW34OEJAQABNWhCIrJFqOz1SZEHI2OGqEarkq8aHWhM66UJSfADpjIZGEAEIqGll5RY4VweHqrWLg4Nc4HBhKK0IOEAtggF9S8oBVDiIhhCtYGUMEF+-w4aFaSwQbkQbEGIBghAIyAQaBgfxgAFtGnoQHA4HDuqYEC54cgliAAG5w5BvMa4iDcMpsEjVHB6Ja2KDokqEcCuFwtJwldEgdFQIgALxAAFonCASl4CAQSgBWACclmCaLoxkQRGoCAADGYOggADxNMJ9ZarY7GogAantpwSwTKvC+Pw440VwgQIFwhBISJqdX4Lo6XXoTH2oiI4k220SeytHFjmgQZ3OFxx11u90e4deLwSl1zSBgOALr0s4Gg8AQbTuOAIiBs5HsjkowtFEpAAHkGKaAEogDjNuAUP1gPHkFqNWgjIhpFQxcjSJYb0KKZcZWLpqi6EdXG4AFVQIGHo-HFG02kCwUXO9UIni2bHLYoPBH74na9mvgDAgeD8QMyEoGgXHcFMQIIeIcgQb9ryKBIdSTOAT2qJcomfcwUJxNDt2w1cJH1CQngGRBdjgRCWy-HNT3PS8fxvcjUNsBFWgHWwQFyQxjEJGg7gIB4LBpPQ+X4b42CqPAQwQRhakoDlyDxac6EfLR-hcNgcGFFTGhqUwYQSNsOycBBuzFSUWgXTCn1XddNyYQj0hwiR4KPXMzzQJikN0TNgjmWh2MVTj23QAAyCK0IwpdqETR8ECijoAP8KMWHYDhpCo7cNGdLNs2PSgqJouByOLcM3QwmBhCkhtrjqwk5C+NhyD0xA8AMeBGhGdBmqIVr2p4ao6QZEoOTaNByCWRxuWMMA+RgAVyHlQYSiHABNABpKA8HFSrygAETFH5erQ0qiQ4Fq2sGVsiBgeQEA4SoRjwXUuhIboasYDgDoqRcfkYIhFX0dAoEpGBGBgEgZ3DEqrxbfVXGY6a8AgCBEVspdpC3TKNHKmTQpaLj0BoOAKwLLMqNixoybsgmcsy-Vcc4AnSxuc6EbKhJq0KstaEs3sWkuhCuYofHgFeIA)

**Comment by alexreardon** [comment]
Need to consider what build changes to be made, and how to continue to support flow consumers

**Comment by TrySound** [comment]
Same as before
https://github.com/renatorib/react-powerplug/blob/master/package.json#L16
https://github.com/renatorib/react-powerplug/tree/master/src

Or just copy this flow file to the dist.
