### ISSUE TITLE
Does memoize-one support Promises?

### ISSUE THREAD

**Issue by bdurrer** [alexreardon/memoize-one#76]
We use memoize-one for almost two years with promises just fine, but looking at the code now I realized that it maybe is not intended or tested to work with them. But maybe all that's missing is an description of `fn` in the readme (?) 

The mentioned error handling likely never was triggered, since promises fall into an error state instead of throwing an error.

**Comment by kirilldronkin** [comment]
+1 to the subject, this aspect forced me replace `memoize-one` to local fork with something like this in the code:

```js
if (called && !rejected && sameThis && sameArgs) {
  return lastResult;
}

// ...

// Quack! Quack! 🦆 
if (typeof (lastResult as any).then === 'function') {
  const pendingPromise = lastResult as PromiseLike<any>;
  pendingPromise.then(null, () => {
    // Avoid a stale cache dropping
    if (pendingPromise === lastResult) {
      rejected = true;
    }
  });
}
```

and I will very glad to see promises support!

**Comment by alexreardon** [comment]
https://github.com/microlinkhq/async-memoize-one might be what you are after

**Comment by alexreardon** [comment]
For now, I have no plans to add promise support to this tiny library. I recommend using the async version linked
