### ISSUE TITLE
TypeError: memoizeOne is not a function

### ISSUE THREAD

**Issue by zhaoxuyll** [alexreardon/memoize-one#80]
Error when packaging using Webpack.
```
e:\weizhi\server\dist\webpack:\node_modules\@metascraper\helpers\index.js:234
const jsonld = memoizeOne((url, $) => {
^
TypeError: memoizeOne is not a function
    at Object../node_modules/@metascraper/helpers/index.js (e:\weizhi\server\dist\webpack:\node_modules\@metascraper\helpers\index.js:234:1)
    at __webpack_require__ (e:\weizhi\server\dist\webpack:\webpack\bootstrap:25:1)
    at Object../node_modules/metascraper/src/index.js (e:\weizhi\server\dist\webpack:\node_modules\metascraper\src\index.js:3:19)
    at __webpack_require__ (e:\weizhi\server\dist\webpack:\webpack\bootstrap:25:1)
```

When "module" (ESM) is used in the "package.json" file of "memoize-one", Webpack will parse it first, but Nodejs "require" no support "exports default",
I can only do this require('memoize-one').default to get rid of errors.

**Comment by TrySound** [comment]
@zhaoxuyll This is the problem with `@metascraper/helpers` package. It should provide esm via `module` field too. To solve the problem you need to disable module field. No sure if it's possible for particular package.
```
module.exports = {
  //...
  resolve: {
    mainFields: ['browser', /*'module', */'main']
  }
};
```

**Comment by zhaoxuyll** [comment]
Thank you very much.

**Comment by Kikobeats** [comment]
I faded with this issue.

`@metascraper/helpers` don't export a "module" because the code is CommonJS.

It should be resolved after this commit https://github.com/microlinkhq/metascraper/commit/f0d2d5e469f8775d155509bd5b264aaae3a5018b

**Comment by The-Code-Monkey** [comment]
This seems to still be an issues in v6 any room to fix this? errors when running jest but compiles fine
