### ISSUE TITLE
Same parameters, different locations will also rerun

### ISSUE THREAD

**Issue by VitaminCtea** [alexreardon/memoize-one#87]
According to the official example:
```
const add = (a, b) => a + b;
const memoizedAdd = memoizeOne(add);
memoizedAdd(1, 2); // 3
```
When I try to switch the position of the argument, instead of taking the cached result, I get a new result, which is also 3!

Like this:
`memoizedAdd(2, 1); // 3`

Read the source code, found when comparing the parameters of the code, should not be such a comparison. If it's a shallow comparison, I think it should be like this:
```
export default function areInputsEqual(
  newInputs: readonly unknown[],
  lastInputs: readonly unknown[],
): boolean {
  // no checks needed if the inputs length has changed
  if (newInputs.length !== lastInputs.length) {
    return false;
  }
  // Using for loop for speed. It generally performs better than array.every
  // https://github.com/alexreardon/memoize-one/pull/59

  // Like this
  if (!newInputs.every(arg => lastInputs.includes(arg))) {
    return false;
  }
  return true;
}
```
In this way, even if the same parameter, and the parameter position changes, the result should be the result of the cache, not the new result! After all, the results are the same.

Welcome the author of the library to communicate and correct, thank you!

**Comment by zaalbarxx** [comment]
I think there is a reason for custom equality check option being available. You can craft it just the way you'd like it to work for you. I am pretty sure not every use case would satisfy your assumption that arguments order is not important :)

**Comment by VitaminCtea** [comment]
@zaalbarxx Ok, thank you for your answer!
