### ISSUE TITLE
Memoize one is failing within a test environment. Value is not changed yet memoized function is called.

### ISSUE THREAD

**Issue by 814k31** [alexreardon/memoize-one#91]
I have zipped an example project to demonstrate the bug.

![react-test-memoize-one](https://user-images.githubusercontent.com/9160551/85514759-f433ae80-b62e-11ea-9e27-acc1834e5184.gif)

The issue only occurs when I run a test using `npm test`. If you run the project normally it works as expected (`npm start`)

Tally is the value that gets incremented using memoize when the button clicks value changes

Within my test environment, it appears the comparison of memoize is ignored and the underlying function is called. I have not set up any mocks to alter the behaviour. Because I use memoize within componentDidUpdate and am updating the state within my memoized function I am receiving an infinite loop `ONLY` in my test environment

Dependencies (as listed in the examples package.json)
"@testing-library/jest-dom": "^4.2.4",
"@testing-library/react": "^9.5.0",
"@testing-library/user-event": "^7.2.1",
"enzyme": "^3.11.0",
"enzyme-adapter-react-16": "^1.15.2",
"memoize-one": "^5.1.1",

Environment:
Node: Tested on: 12.18.1 (lts, stable) and 14.4.0 (latest)

[react-test-memoize-one.zip](https://github.com/alexreardon/memoize-one/files/4823722/react-test-memoize-one.zip)

**Comment by alexreardon** [comment]
I have not been able to replicate this behaviour. Can you please provide some more information?

**Comment by alexreardon** [comment]
Feel free to comment if this is still a problem for you
