### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by matthewoates** [alexreardon/memoize-one#96]
```
const shallowMemoized = memoizeOne(identity);
const deepMemoized = memoizeOne(identity, isDeepEqual);

const result1 = shallowMemoized({ foo: 'bar' });
const result2 = shallowMemoized({ foo: 'bar' });
```

This isn't a shallow comparison - it's a reference comparison. Checking each key in the object for equality (by reference) would be a shallow comparison.

**Comment by alexreardon** [comment]
Good call, it's before default it's just checking the reference. Would you like to raise a PR?

**Comment by dperetti** [comment]
Also `import memoizeOne from 'memoize-one'`, not `import { memoizeOne } from 'memoize-one'` ?

**Comment by alexreardon** [comment]
`memoize-one` now supports a named import
